# Signal-Rich Strategy - More signals with lower precision
# BB OR MACD conditions (not both)
bollinger: {length: 20, std: 1.8}
macD: {fast: 12, slow: 26, signal: 9}
rsi: {length: 14, use_filter: false, rsi_buy_max: 45, rsi_sell_min: 55}
filters:
  ema_trend:
    use: false
    length: 50
    mode: long_only_above
execution: {touch_tolerance_pct: 0.005, slippage_pct: 0.0005, fee_pct: 0.0004}
risk: {use_atr: false, atr_length: 14, stop_mult: 1.0, trail_mult: 1.5}
exits: {time_based: {use: true, max_bars_in_trade: 100}, midband_exit: {use: false}}
backtest: {initial_cash: 10000, size_pct: 0.95, allow_short: false, plot: true}