# Quality Over Quantity Strategy - High precision, low frequency
# Focus on high-quality signals with multiple confirmations
bollinger: {length: 20, std: 2.2}
macD: {fast: 12, slow: 26, signal: 9}
rsi: {length: 14, use_filter: true, rsi_buy_max: 35, rsi_sell_min: 65}
filters:
  ema_trend:
    use: true
    length: 200
    mode: long_only_above
execution: {touch_tolerance_pct: 0.002, slippage_pct: 0.0005, fee_pct: 0.0004}
risk: {use_atr: true, atr_length: 14, stop_mult: 2.0, trail_mult: 2.5}
exits: {time_based: {use: true, max_bars_in_trade: 200}, midband_exit: {use: false}}
backtest: {initial_cash: 10000, size_pct: 0.80, allow_short: false, plot: true}