# Volatility Breakout Strategy - Trade volatility expansions
# Uses Bollinger squeeze, Keltner channels, volume expansion
bollinger: {length: 20, std: 2.0}
macD: {fast: 12, slow: 26, signal: 9}
rsi: {length: 14, use_filter: false, rsi_buy_max: 50, rsi_sell_min: 50}
filters:
  ema_trend:
    use: false
    length: 200
    mode: long_only_above
execution: {touch_tolerance_pct: 0.008, slippage_pct: 0.0005, fee_pct: 0.0004}
risk: {use_atr: true, atr_length: 14, stop_mult: 1.8, trail_mult: 2.2}
exits: {time_based: {use: true, max_bars_in_trade: 100}, midband_exit: {use: true}}
backtest: {initial_cash: 10000, size_pct: 0.90, allow_short: false, plot: true}