# Trend Momentum Strategy - Follow strong trends with momentum
# Uses Supertrend, ADX, and volume confirmation
bollinger: {length: 20, std: 2.0}
macD: {fast: 8, slow: 21, signal: 7}
rsi: {length: 14, use_filter: true, rsi_buy_max: 70, rsi_sell_min: 30}
filters:
  ema_trend:
    use: true
    length: 50
    mode: long_only_above
execution: {touch_tolerance_pct: 0.005, slippage_pct: 0.0005, fee_pct: 0.0004}
risk: {use_atr: true, atr_length: 14, stop_mult: 1.5, trail_mult: 2.0}
exits: {time_based: {use: true, max_bars_in_trade: 150}, midband_exit: {use: false}}
backtest: {initial_cash: 10000, size_pct: 0.85, allow_short: false, plot: true}